server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.info.headers: false

    consumer:
      group-id: inventory-group
      auto-offset-reset: latest
      # No deserializer config here — handled by KafkaConfig beans above

    type: simple   # ADD THIS — use of  @Cacheable/@CacheEvict but never declared a cache manager